"""add verify email

Revision ID: 1a86f73341dc
Revises: c451df8a2cc5
Create Date: 2025-03-08 15:50:46.869285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a86f73341dc'
down_revision: Union[str, None] = 'c451df8a2cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'confirmed')
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.add_column('contacts', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
