"""add reletionship

Revision ID: 62de54964549
Revises: 06e4255e0bc0
Create Date: 2025-03-06 21:47:58.192620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62de54964549'
down_revision: Union[str, None] = '06e4255e0bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('contacts', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'contacts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.alter_column('contacts', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('contacts', 'owner_id')
    # ### end Alembic commands ###
